workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    integrations:
      app_store_connect: Tots Paris1 # Ensure this matches your Codemagic Team Integration name

    environment:
      groups:
        - apple_auth        # Group containing your Apple API keys
        - firebase_config   # Group containing IOS_FIREBASE_SECRET
      vars:
        BUNDLE_ID: "com.dv.totsparis"
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e
          # Recreate the plist file from the secret variable to prevent startup crash
          echo "$IOS_FIREBASE_SECRET" > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Fetch signing files
        script: |
          # Automatically manages certificates and profiles for your bundle ID
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Set up code signing settings
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          flutter packages pub get
          # Mandatory for OneSignal and Firebase on iOS
          cd ios && pod install && cd ..

      - name: Build iOS IPA
        script: | 
          # Build with automatic versioning to avoid App Store rejection
          flutter build ipa --release \
            --bundle-name="Tots Paris" \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=$HOME/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # Optional: Add your beta_groups here
