workflows:
  ios-adhoc:
    name: iOS AdHoc IPA
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Fetch AdHoc signing files
        script: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
            --platform IOS \
            --type IOS_ADHOC \
            --create

      - name: Add certificates
        script: |
          keychain add-certificates

      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          flutter pub get
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
