workflows:
  ios-adhoc:
    name: iOS AdHoc IPA (Real Device Testing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
      vars:
        BUNDLE_ID: "com.totsparis"  # Replace with your actual bundle ID
      
      ios_signing:
        distribution_type: adhoc
        bundle_identifier: com.totsparis  # Replace with your bundle ID
    
    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize
      
      # 🔥 CREATE FIREBASE PLIST
      - name: Create GoogleService-Info.plist
        script: |
          if [ -z "$IOS_FIREBASE_SECRET" ]; then
            echo "❌ ERROR: IOS_FIREBASE_SECRET environment variable is not set!"
            exit 1
          fi
          
          echo "$IOS_FIREBASE_SECRET" > ios/Runner/GoogleService-Info.plist
          
          if [ ! -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "❌ ERROR: GoogleService-Info.plist was not created!"
            exit 1
          fi
          
          echo "✅ GoogleService-Info.plist created successfully"
      
      # 🔥 FETCH SIGNING
      - name: Fetch AdHoc signing files
        script: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
            --platform IOS \
            --type IOS_ADHOC \
            --create
      
      - name: Add certificates
        script: |
          keychain add-certificates
      
      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles
      
      # 🔥 CRITICAL: Deep clean before install
      - name: Deep clean project
        script: |
          echo "🧹 Deep cleaning project..."
          
          # Clean Flutter
          flutter clean
          
          # Remove all build artifacts
          rm -rf build/
          rm -rf .dart_tool/
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          
          echo "✅ Deep clean completed"
      
      # 🔥 INSTALL DEPENDENCIES
      - name: Install dependencies
        script: |
          echo "📦 Getting Flutter dependencies..."
          flutter pub get
          
          echo "📦 Installing CocoaPods dependencies..."
          cd ios
          pod install --repo-update --verbose
          cd ..
          
          echo "✅ Dependencies installed"
      
      # 🔥 VALIDATE BEFORE BUILD
      - name: Validate configuration
        script: |
          # Validate Firebase plist
          if ! grep -q "GOOGLE_APP_ID" ios/Runner/GoogleService-Info.plist; then
            echo "❌ ERROR: Invalid GoogleService-Info.plist"
            exit 1
          fi
          
          # Validate main.dart syntax
          echo "🔍 Validating Dart code..."
          flutter analyze --no-fatal-infos --no-fatal-warnings
          
          echo "✅ Validation passed"
      
      # 🔥 BUILD IPA (with verbose output)
      - name: Build IPA
        script: |
          echo "🔨 Building iOS IPA..."
          
          # Build with verbose output to see exact error
          flutter build ipa \
            --release \
            --verbose \
            --export-options-plist=/Users/builder/export_options.plist
          
          if [ $? -ne 0 ]; then
            echo "❌ Build failed"
            exit 1
          fi
          
          echo "✅ IPA built successfully"
          ls -lh build/ios/ipa/
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive/dSYMs/*.dSYM
    
    publishing:
      scripts:
        - name: Upload dSYMs to Firebase Crashlytics
          script: |
            echo "📤 Uploading dSYMs to Firebase Crashlytics..."
            
            dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive/dSYMs -name "*.dSYM" | head -1)
            
            if [[ -z "$dsymPath" ]]; then
              echo "⚠️ WARNING: No dSYM found, skipping upload"
              exit 0
            fi
            
            if [ -f "$CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols" ]; then
              $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols \
                -gsp $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist \
                -p ios "$dsymPath"
              
              echo "✅ dSYMs uploaded successfully"
            else
              echo "⚠️ WARNING: FirebaseCrashlytics upload-symbols script not found"
            fi
