workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    integrations:
      app_store_connect: Tots Paris1 

    environment:
      groups:
        - apple_auth       
        - firebase_config  
      vars:
        BUNDLE_ID: "com.dv.totsparis"
      flutter: 3.24.4     
      xcode: 16.1         
      cocoapods: default

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Load Firebase configuration
        script: |
          mkdir -p $CM_BUILD_DIR/ios/Runner
          echo "$IOS_FIREBASE_SECRET" > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Force iOS 15.0 in Project Files
        script: |
          # 1. Edit Podfile: Change platform to 15.0 (handles commented and uncommented lines)
          sed -i '' "s/^# platform :ios, .*/platform :ios, '15.0'/" ios/Podfile
          sed -i '' "s/^platform :ios, .*/platform :ios, '15.0'/" ios/Podfile
          
          # 2. Edit Xcode Project: Force all target versions to 15.0
          find ios/Runner.xcodeproj/project.pbxproj -type f -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' {} +

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Set up code signing settings
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          flutter packages pub get
          cd ios
          # Deep clean to ensure the 15.0 change is recognized
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS IPA
        script: | 
          # Using --release is mandatory; --debug will cause version mismatch errors
          flutter build ipa --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=$HOME/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
