workflows:
  ios-adhoc:
    name: iOS AdHoc IPA (Real Device Testing)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize

      # 🔥 CREATE FIREBASE PLIST (CRITICAL)
      - name: Create GoogleService-Info.plist
        script: |
          echo "$IOS_FIREBASE_SECRET" > ios/Runner/GoogleService-Info.plist

      # 🔥 FETCH AD-HOC SIGNING (NOT APP STORE)
      - name: Fetch AdHoc signing files
        script: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
            --platform IOS \
            --type IOS_ADHOC \
            --create

      - name: Add certificates
        script: |
          keychain add-certificates

      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      # ✅ BUILD AD-HOC IPA
      - name: Build IPA (Release / AdHoc)
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
