workflows:
  ios-release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    integrations:
      app_store_connect: Tots Paris1 # Double-check this name in Codemagic UI

    environment:
      groups:
        - apple_auth       # Group containing your Apple API keys
        - firebase_config  # Group containing IOS_FIREBASE_SECRET
      vars:
        BUNDLE_ID: "com.dv.totsparis"
      flutter: 3.24.4     # Pinned for stability
      xcode: 16.1         # Pinned for stability
      cocoapods: default

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e
          # Ensure directory exists and recreate the plist from the secret
          mkdir -p $CM_BUILD_DIR/ios/Runner
          echo "$IOS_FIREBASE_SECRET" > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Fetch signing files
        script: |
          # Automatically manages certificates and profiles
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Set up code signing settings
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          flutter packages pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS IPA
        script: | 
          # PROJECT_BUILD_NUMBER ensures you never upload the same version twice
          flutter build ipa --release \
            --bundle-name="Tots Paris" \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=$HOME/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
