workflows:
  ios-adhoc:
    name: iOS AdHoc IPA (Real Device Testing)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.14.3  # Use a known recent stable version

    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Create GoogleService-Info.plist
        script: |
          echo "$IOS_FIREBASE_SECRET" > ios/Runner/GoogleService-Info.plist

      - name: Fetch AdHoc signing files
        script: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
            --platform IOS \
            --type IOS_ADHOC \
            --create

      - name: Add certificates
        script: |
          keychain add-certificates

      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Install dependencies
        script: |
          flutter pub get

          # Clean up outdated pods & lock file
          rm -rf ios/Pods
          rm -f ios/Podfile.lock

          cd ios

          echo "Updating CocoaPods specs repository..."
          pod repo update

          echo "Installing pods..."
          pod install

          cd ..

      - name: Build IPA (Release / AdHoc)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

publishing:
  scripts:
    - name: Upload dSYMs to Firebase
      script: |
        dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive/dSYMs -name "Runner.app.dSYM" | head -1)
        if [[ -z "$dsymPath" ]]; then
          echo "No dSYM found"
        else
          echo "Uploading dSYM to Firebase Crashlytics..."
          $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols --build-phase --validate -ai 1:1091304297452:ios:7e5f2b7c24490690ae66c9 -- $dsymPath
        fi
